/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface Transaction {
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface User {
  'balance' : bigint,
  'displayName' : string,
  'transactions' : Array<Transaction>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'allocatePoints' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllTransactionsByAmount' : ActorMethod<[], Array<Transaction>>,
  'getAllTransactionsByRecipient' : ActorMethod<[], Array<Transaction>>,
  'getAllTransactionsBySender' : ActorMethod<[], Array<Transaction>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAllUsersByBalance' : ActorMethod<[], Array<User>>,
  'getAllUsersByDisplayName' : ActorMethod<[], Array<User>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendPoints' : ActorMethod<[Principal, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];